### ISSUE TITLE
Broken Pypi Access? Repo Still Under Maintenance (OR Archived Already?)

### ISSUE THREAD

**Issue by marridG** [yuxiqian/electsys-api#3]
**Bug 描述**
Pypi 官网找不到发布的包，直接按 usage pip install 也 package not found

**Bug 复现**
\# 令 Bug 出现的具体步骤/代码片段

**预期的行为**

**环境信息**
 - 操作系统: [e.g. Windows]
 - Python 版本 [e.g. 3.7.2, [Clang 9.0.0 (clang-900.0.39.2)] on darwin]
 - API 版本 [e.g. 0.0.2]

**更多信息**

**Comment by yuxiqian** [comment]
It was removed deliberately. You may try [pysjtu](https://github.com/PhotonQuantum/pysjtu) instead.
